/**
 * Defines the lifecycle policy of a service within the DI container.
 * - `singleton`: Instantiated once per container definition (shared globally across all scopes).
 * - `scoped`: Instantiated once per `ServiceProvider` instance (shared locally within a scope).
 * - `transient`: Instantiated every time it is resolved (never cached).
 */
export type ServiceLifetime = 'singleton' | 'transient' | 'scoped';

/**
 * A branded string type representing a unique key for a service, retaining its underlying type definition.
 * @template T The expected type of the resolved service.
 */
export type ServiceKey<T> = string & { __type: T };

/**
 * Describes how a service should be created and managed by the container.
 * * @template T The type of the service.
 */
export type ServiceDescriptor<T> = {
    /** The lifecycle rule governing the service's caching behavior. */
    lifetime: ServiceLifetime;
    /** The factory function responsible for instantiating the service. */
    factory: (sp: ServiceProvider) => T;
};

/**
 * A registry mapping service names (keys) to their corresponding descriptors.
 * * @template TServiceMap A record defining the contract of all available services.
 */
export type ServiceRegistry<TServiceMap extends Record<ServiceKey<any>, any>> = {
    [K in keyof TServiceMap]: ServiceDescriptor<TServiceMap[K]>;
};

// --- Helpers for clean configuration ---

/**
 * Registers a service with a 'singleton' lifetime.
 * The service will be created once and shared across all scopes generated by the container.
 * @template T The type of the service.
 * @param {(sp: ServiceProvider) => T} factory The function to instantiate the service.
 * @returns {ServiceDescriptor<T>} The configured service descriptor.
 */
export const addSingleton = <T>(factory: (sp: ServiceProvider) => T): ServiceDescriptor<T> => ({ lifetime: 'singleton', factory });

/**
 * Registers a service with a 'scoped' lifetime.
 * The service will be created once per `ServiceProvider` instance.
 * @template T The type of the service.
 * @param {(sp: ServiceProvider) => T} factory The function to instantiate the service.
 * @returns {ServiceDescriptor<T>} The configured service descriptor.
 */
export const addScoped = <T>(factory: (sp: ServiceProvider) => T): ServiceDescriptor<T> => ({ lifetime: 'scoped', factory });

/**
 * Registers a service with a 'transient' lifetime.
 * A new instance of the service will be created every time it is requested.
 * @template T The type of the service.
 * @param {(sp: ServiceProvider) => T} factory The function to instantiate the service.
 * @returns {ServiceDescriptor<T>} The configured service descriptor.
 */
export const addTransient = <T>(factory: (sp: ServiceProvider) => T): ServiceDescriptor<T> => ({ lifetime: 'transient', factory });

/**
 * The core container interface responsible for resolving registered services.
 */
export type ServiceProvider = {
    /**
     * Resolves a service by its key. Throws an error if the service is not found.
     * @template T The expected return type of the service.
     * @param {ServiceKey<T> | string} key The key identifying the service.
     * @returns {T} The resolved service instance.
     * @throws {Error} If the service is not registered or if a circular dependency is detected.
     */
    resolve: <T>(key: ServiceKey<T> | string) => T;

    /**
     * Attempts to resolve a service by its key. Returns null if not found.
     * @template T The expected return type of the service.
     * @param {ServiceKey<T> | string} key The key identifying the service.
     * @returns {T | null} The resolved service instance, or null if unregistered.
     * @throws {Error} If a circular dependency is detected during resolution.
     */
    locate: <T>(key: ServiceKey<T> | string) => T | null;
}

/**
 * An intersection type combining the `ServiceProvider` interface with the actual service map.
 * This allows the provider to be destructured dynamically via a Proxy.
 * @template TServiceMap The record of available services.
 */
export type MapServiceProvider<TServiceMap> = ServiceProvider & TServiceMap;

/**
 * Defines and configures a new functional Service Container.
 * This function utilizes closures to maintain a global singleton cache shared across all created scopes.
 * @template TServiceMap A record defining the available services and their types.
 * @param {ServiceRegistry<TServiceMap>} services The registry of configured service descriptors.
 * @returns {() => MapServiceProvider<TServiceMap>} A factory function. Invoking this function creates a new `ServiceProvider` instance (a new scope).
 */
export function defineServiceContainer<TServiceMap extends Record<ServiceKey<any> | string, any>>(
    services: ServiceRegistry<TServiceMap> 
): () => MapServiceProvider<TServiceMap> {

    // Global to ALL providers
    const singletonCache = {} as Record<string, any>;

    // Calling this creates a new Scope
    return function createProvider(): MapServiceProvider<TServiceMap> {
        const resolutionStack = new Set<string>(); 
        
        // Local to THIS specific provider
        const scopedCache = {} as Record<string, any>; 
        
        const provider: ServiceProvider = {
            locate: <T>(key: ServiceKey<T> | string): T | null => {
                const typedKey = key as string;
                const descriptor = services[typedKey as keyof TServiceMap];
                
                if (!descriptor) return null;

                if (resolutionStack.has(typedKey)) {
                    throw new Error(`Circular dependency detected: ${Array.from(resolutionStack).join(' -> ')} -> ${typedKey}`);
                }

                // 1. SINGLETON: Check the global cache
                if (descriptor.lifetime === "singleton") {
                    if (singletonCache[typedKey]) {
                        return singletonCache[typedKey] as T;
                    }
                    
                    resolutionStack.add(typedKey);
                    const created = descriptor.factory(provider);
                    resolutionStack.delete(typedKey);
                    
                    singletonCache[typedKey] = created;
                    return created as T;
                }

                // 2. SCOPED: Check the local cache
                if (descriptor.lifetime === "scoped") {
                    if (scopedCache[typedKey]) {
                        return scopedCache[typedKey] as T;
                    }
                    
                    resolutionStack.add(typedKey);
                    const created = descriptor.factory(provider);
                    resolutionStack.delete(typedKey);
                    
                    scopedCache[typedKey] = created;
                    return created as T;
                }

                // 3. TRANSIENT: Never cache
                resolutionStack.add(typedKey);
                const created = descriptor.factory(provider);
                resolutionStack.delete(typedKey);
                
                return created as T;
            },

            resolve: <T>(key: ServiceKey<T> | string): T => {
                const service = provider.locate<T>(key);
                if (!service) throw new Error(`Service '${key as string}' not registered.`);
                return service;
            },
        };

        return new Proxy(provider as MapServiceProvider<TServiceMap>, {
            get(target, prop, receiver) {
                if (prop === 'resolve' || prop === 'locate') {
                    return Reflect.get(target, prop, receiver);
                }
                if (typeof prop === 'symbol') {
                    return Reflect.get(target, prop, receiver);
                }
                if (prop === 'then') {
                    return undefined; // Prevent issues with Promise-like behavior
                }
                return target.resolve(prop);
            }
        });
    }
}

/**
 * A fluent builder interface for configuring a ServiceProvider, inspired by .NET's IServiceCollection.
 * 
 * It incrementally builds the service map type (TMap) as services are registered, ensuring strict type safety.
 * 
 * **NOTE:** Due to the way the Map type accumulates Records, you may only retrieve services in factories that have already been 
 * registered. Not only that but the ending type may be quite clutered if you have lots of anonymous (untyped) services. 
 * Use the manually defined TMap approach if you prefer something cleaner or unordered registration support.
 * @template TMap The accumulated record of services registered so far.
 */
export type ServiceCollection<TMap extends Record<string, any> = {}> = {
    /**
     * Registers a service with a 'singleton' lifetime.
     * @param key The string identifier for the service.
     * @param factory The factory function. The injected provider knows about all previously registered services.
     */
    addSingleton<K extends string, T>(
        key: K, 
        factory: (sp: MapServiceProvider<TMap>) => T
    ): ServiceCollection<TMap & Record<K, T>>;
    
    /**
     * Registers a service with a 'scoped' lifetime.
     * @param key The string identifier for the service.
     * @param factory The factory function.
     */
    addScoped<K extends string, T>(
        key: K, 
        factory: (sp: MapServiceProvider<TMap>) => T
    ): ServiceCollection<TMap & Record<K, T>>;

    /**
     * Registers a service with a 'transient' lifetime.
     * @param key The string identifier for the service.
     * @param factory The factory function.
     */
    addTransient<K extends string, T>(
        key: K, 
        factory: (sp: MapServiceProvider<TMap>) => T
    ): ServiceCollection<TMap & Record<K, T>>;

    /**
     * Compiles the registered services into a functional container factory.
     * @returns A factory function that generates containers (`MapServiceProvider`).
     */
    build(): () => MapServiceProvider<TMap>;
}

/**
 * Creates a new, empty ServiceCollection to begin fluent registration.
 */
export function createServiceCollection(): ServiceCollection {
    // Internal mutable registry hidden within the closure
    const registry = {} as ServiceRegistry<any>;

    const builder: ServiceCollection<any> = {
        addSingleton(key, factory) {
            registry[key] = { lifetime: 'singleton', factory };
            return this;
        },
        addScoped(key, factory) {
            registry[key] = { lifetime: 'scoped', factory };
            return this;
        },
        addTransient(key, factory) {
            registry[key] = { lifetime: 'transient', factory };
            return this;
        },
        build() {
            // Hand the fully populated registry off to our core container logic
            return defineServiceContainer(registry);
        }
    };

    return builder;
}